### ISSUE TITLE
Add support for Bezier animation tracks

### ISSUE THREAD

**Issue by lpszmoths** [samdze/godot-modifiers-plugin#1]
## Repro steps

1. Create a new scene starting from an empty Spatial root node
2. Add a Spatial node and rename it `ModifiersTarget`
3. Add and configure the Modifiers node
3.1. Add a Modifiers node and rename it `Modifiers`
3.2. In the Modifiers inspector, set `ModifiersTarget` as the target of `Modifiers`
3.3. In the Modifiers inspector, click on **Add Property**
3.4. Select the Transform property
3.5. Click on **Add Modifier**
3.6. Name the new modifier `TargetTransform`
4. Animation player setup
4.1. Add an AnimationPlayer to the scene
4.2. Create a new animation named `Scale`
4.3. Open the animation bottom panel and click on **Add Track** 
4.4. Select **Bezier Curve Track**
4.5. Select the `Modifiers` node.

## Actual result

The modifier we created does not appear on the list, so I can't animate it with a Bezier track.

![image](https://user-images.githubusercontent.com/119032428/219142453-dc48b8ce-3d3f-412c-9627-3712d0eb9d37.png)

## Expected result

When you create a new Bezier curve track, you should be able to see Modifiers nodes, select their modifiers, and animate them.

I haven't taken a look at the code so I'm not sure if this is dependent on https://github.com/godotengine/godot-proposals/issues/300

Otherwise great plugin!

**Comment by samdze** [comment]
I'll take a look, may be a Godot bug.

**Comment by samdze** [comment]
Alright, I see, it's not that the Modifiers plugin doesn't support Bezier animation tracks, It's Bezier tracks that don't support the Transform type, of course.

The default editor property selector shows extra properties for Spatial nodes (and other types of nodes too).
Right now the plugin shows non-computed properties only, but I'll update it so that the property selector also shows those extra ones!

**Comment by samdze** [comment]
Fixed by 3d2c222cf8caf2b7f4673073db3d74623c95c110
